[project]
name = "graceful-labelling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ipytest>=0.14.2",
    "matplotlib>=3.10.3",
    "networkx>=3.5",
    "pytest>=8.4.0",
]
